#pragma once
#define BT_DEBUG_VERBOSE
 
#include "BT_NODE.h"
#include "BT_LEAF.h"
#include "BT_ACTION.h"
#include "BT_DECORATOR.h"

//Composite notes
#include "BT_SEQUENCER.h"
#include "BT_SELECTOR.h"
#include "BT_PARALLEL_SEQUENCER.h"
#include "BT_PARALLEL_SELECTOR.h"

//Decorators
#include "BT_DECO_CONDITION.h"
#include "BT_DECO_INVERTER.h"
#include "BT_DECO_REPEATER.h"
#include "BT_DECO_RETURN_FAILURE.h"
#include "BT_DECO_RETURN_SUCCESS.h"
#include "BT_DECO_UNTIL_FAILURE.h"
#include "BT_DECO_UNTIL_SUCCESS.h"

///Conditions
#include "BT_STARCRAFT/BT_DECO_CONDITION_NOT_ENOUGH_WORKERS_FARMING_MINERALS.h"
#include "BT_STARCRAFT/BT_DECO_CONDITION_NOT_ENOUGH_WORKERS_FARMING_GAS.h"
#include "BT_STARCRAFT/BT_DECO_CONDITION_NOT_ENOUGH_WORKERS.h"
#include "BT_STARCRAFT/BT_DECO_CONDITION_NOT_ENOUGH_ZERGLINGS.h"
#include "BT_STARCRAFT/BT_DECO_CONDITION_NOT_ENOUGH_MUTALISKS.h"
#include "BT_STARCRAFT/BT_DECO_CONDITION_NOT_ENOUGH_SUPPLY.h"
#include "BT_STARCRAFT/BT_DECO_CONDITION_NOT_ENOUGH_SPAWNING_POOL.h"
#include "BT_STARCRAFT/BT_DECO_CONDITION_NOT_ENOUGH_EXTRACTOR.h"
#include "BT_STARCRAFT/BT_DECO_CONDITION_NOT_ENOUGH_SPIRE.h"
#include "BT_STARCRAFT/BT_DECO_CONDITION_READY_TO_HARASS.h"
#include "BT_STARCRAFT/BT_DECO_CONDITION_READY_TO_ATTACK.h"

///Actions
#include "BT_ACTION_IDLE.h"
#include "BT_ACTION_WAIT.h"
#include "BT_STARCRAFT/BT_ACTION_SEND_IDLE_WORKER_TO_MINERALS.h"
#include "BT_STARCRAFT/BT_ACTION_SEND_IDLE_WORKER_TO_GAS.h"
#include "BT_STARCRAFT/BT_ACTION_TRAIN_WORKER.h"
#include "BT_STARCRAFT/BT_ACTION_TRAIN_ZERGLING.h"
#include "BT_STARCRAFT/BT_ACTION_TRAIN_MUTALISK.h"
#include "BT_STARCRAFT/BT_ACTION_BUILD_SUPPLY_PROVIDER.h"
#include "BT_STARCRAFT/BT_ACTION_BUILD_SPAWNING_POOL.h"
#include "BT_STARCRAFT/BT_ACTION_BUILD_EXTRACTOR.h"
#include "BT_STARCRAFT/BT_ACTION_BUILD_SPIRE.h"
#include "BT_STARCRAFT/BT_ACTION_HARASS.h"
#include "BT_STARCRAFT/BT_ACTION_ATTACK.h"



